### ISSUE TITLE
Upgrade to recent version

### ISSUE THREAD

**Issue by JaRoSchm** [conda-forge/envisage-feedstock#23]
### Comment:

Hi,

is this feedstock still maintained and would it be possible to upgrade to a more recent version? In my case I would need the fix https://github.com/enthought/envisage/pull/485 which should be included in versions >= 6.1.1. There are already some pull requests from the bot existent.

**Comment by JaRoSchm** [comment]
@conda-forge/core Could someone please merge the corresponding pull requests? It seems like the original maintainer is not active here anymore. If wanted, you can add me as a maintainer (although the two feedstocks I maintain didn't require any real work yet). I will ask the bot to create a corresponding PR.

**Comment by xhochy** [comment]
Can you please update one of the PRs so that there is a green CI and add yourself at the same time as a maintainer? Happy to merge those.

**Comment by JaRoSchm** [comment]
@xhochy done in #26, thank you!
